'use strict';
function botProfile(){return({easy:{reaction:.34,horizon:.45,noise:8,depth:0,beam:4},medium:{reaction:.16,horizon:.8,noise:2.1,depth:0,beam:8},hard:{reaction:.065,horizon:1.25,noise:.35,depth:1,beam:10},impossible:{reaction:.025,horizon:1.8,noise:0,depth:2,beam:14}})[difficulty]}
function cloneBoard(b){return b.map(r=>r.slice())}
function boardLanding(type,o,x,b){const p={type,orientation:o,cells:cellsFor(type,o),x,y:-4};if(cellsAt(p,-4,x).some(c=>c.x<0||c.x>=COLS))return null;let y=-pieceHeight(p.cells);while(!boardCollision(p,x,y+1,b))y++;return y}
function placeOnBoard(type,o,x,b){const y=boardLanding(type,o,x,b);if(y==null)return null;const out=cloneBoard(b);let topout=false;for(const [cx,cy] of cellsFor(type,o)){const yy=y+cy,xx=x+cx;if(yy<0)topout=true;else out[yy][xx]=type}let lines=0;for(let r=ROWS-1;r>=0;r--)if(out[r].every(Boolean)){out.splice(r,1);out.unshift(Array(COLS).fill(null));lines++;r++}return{board:out,y,lines,topout,cells:cellsFor(type,o)}}
function forecastBoard(){const b=cloneBoard(grid),fps=[...fallingPieces].sort((a,b)=>b.y-a.y);for(const p of fps){const y=boardLanding(p.type,p.orientation,p.x,b);if(y==null)continue;for(const [cx,cy] of p.cells){const yy=y+cy;if(yy>=0&&yy<ROWS)b[yy][p.x+cx]=p.type}for(let r=ROWS-1;r>=0;r--)if(b[r].every(Boolean)){b.splice(r,1);b.unshift(Array(COLS).fill(null));r++}}return b}
function metrics(b){let holes=0,agg=0,maxH=0,bump=0;const heights=[];for(let x=0;x<COLS;x++){let first=ROWS,seen=false;for(let y=0;y<ROWS;y++){if(b[y][x]){if(first===ROWS)first=y;seen=true}else if(seen)holes++}const h=ROWS-first;heights.push(h);agg+=h;maxH=Math.max(maxH,h)}for(let i=1;i<COLS;i++)bump+=Math.abs(heights[i]-heights[i-1]);return{holes,agg,maxH,bump,heights}}
function threatValue(x,y,cells){const rc=runner.x+runner.w/2;let v=0;for(const [cx,cy] of cells){const px=x+cx+.5,py=y+cy;if(Math.abs(px-rc)<.85){const dy=runner.y-py;if(dy>-.5&&dy<4.5)v+=(4.5-Math.abs(dy))*5}if(py<runner.y&&Math.abs(px-rc)<1.5)v+=2.2}return v}
function evaluatePlacement(type,o,x,b,lookDepth=0){const sim=placeOnBoard(type,o,x,b);if(!sim)return-1e9;const m=metrics(sim.board);let s=sim.lines*32-m.holes*8.8-m.agg*.34-m.bump*.42-m.maxH*.55+(sim.topout?-500:0)+threatValue(x,sim.y,sim.cells)*1.65;const rc=runner.x+runner.w/2,center=x+pieceWidth(sim.cells)/2;s+=Math.max(0,4-Math.abs(center-rc))*1.1;if(lookDepth>0){const next=nextQueue[0];if(next){const future=enumeratePlacements(next,sim.board,0);if(future.length)s+=future[0].score*.22}}return s}
function enumeratePlacements(type,b,lookDepth=0){const arr=[];for(let o=0;o<4;o++){const cells=cellsFor(type,o),w=pieceWidth(cells);for(let x=0;x<=COLS-w;x++)arr.push({type,o,x,score:evaluatePlacement(type,o,x,b,lookDepth)})}arr.sort((a,b)=>b.score-a.score);return arr}
function chooseBlockPlan(){if(!current)return;const p=botProfile(),b=forecastBoard();let candidates=enumeratePlacements(current.type,b,p.depth>0?1:0);if(!candidates.length)return;const top=Math.min(candidates.length,p.beam);let pick;if(difficulty==='easy')pick=candidates[Math.floor(rand()*Math.min(10,top))];else{for(let i=0;i<top;i++)candidates[i].score+=(rand()-.5)*p.noise;pick=candidates.slice(0,top).sort((a,b)=>b.score-a.score)[0]}if(!holdUsed&&(difficulty==='hard'||difficulty==='impossible')){const altType=holdType||nextQueue[0];if(altType){const alt=enumeratePlacements(altType,b,p.depth>0?1:0)[0];if(alt&&alt.score>pick.score+3.5){holdCurrent();candidates=enumeratePlacements(current.type,b,p.depth>0?1:0);pick=candidates[0]}}}current.orientation=pick.o;current.cells=cellsFor(current.type,pick.o);current.x=pick.x;normalizePieceX(current);aiThink=999}
function fallingHazardAt(x,y,horizon){let risk=0;for(const p of fallingPieces){for(const [cx,cy] of p.cells){const col=p.x+cx;if(Math.abs((col+.5)-(x+runner.w/2))>.72)continue;const cellY=p.y+cy,eta=Math.max(0,(y-cellY)/DROP_SPEED);if(eta<=horizon)risk+=(horizon-eta+0.05)*18}}if(current&&selectedRole==='block'){for(const [cx] of current.cells)if(Math.abs((current.x+cx+.5)-(x+runner.w/2))<.72)risk+=4}return risk}
function surfaceY(col){for(let y=0;y<ROWS;y++)if(grid[y][col])return y;return ROWS}
function aabbStaticAt(x,y){const l=Math.floor(x+EPS),r=Math.floor(x+runner.w-EPS),t=Math.floor(y+EPS),b=Math.floor(y+runner.h-EPS);for(let yy=t;yy<=b;yy++)for(let xx=l;xx<=r;xx++)if(solidCell(xx,yy))return true;return false}
function buildTraversalTargets(){const out=[];for(let c=0;c<COLS;c++){const sy=surfaceY(c),x=Math.max(0,Math.min(COLS-runner.w,c+.5-runner.w/2)),y=sy-runner.h-EPS;if(y<ROWS-runner.h+.01&&!aabbStaticAt(x,y))out.push({c,x,y})}return out}
function runnerPlan(){const p=botProfile(),targets=buildTraversalTargets(),rc=runner.x+runner.w/2;let best={score:1e9,x:runner.x,y:runner.y};for(const t of targets){const dx=Math.abs(t.x-runner.x),rise=runner.y-t.y,reachable=rise<=5.0+(Math.abs(t.c-Math.floor(rc))<=1?1.2:0);let score=t.y*3.2+dx*.75+fallingHazardAt(t.x,t.y,p.horizon);if(!reachable)score+=16;if(Math.abs(t.c-Math.floor(rc))>4)score+=3;score+=(rand()-.5)*p.noise;if(score<best.score)best={score,x:t.x,y:t.y}}return best}
function botRunnerInput(dt){const p=botProfile();runner.aiDecision-=dt;if(runner.aiDecision<=0){runner.aiDecision=p.reaction;const plan=runnerPlan();runner.aiTargetX=plan.x;runner.aiTargetY=plan.y}let ix=0,jump=false,dx=runner.aiTargetX-runner.x;if(Math.abs(dx)>.06)ix=Math.sign(dx);const blocked=ix&&aabbStaticAt(Math.max(0,Math.min(COLS-runner.w,runner.x+ix*.08)),runner.y),needRise=(runner.aiTargetY??runner.y)<runner.y-.45,danger=fallingHazardAt(runner.x,runner.y,p.horizon)>(difficulty==='easy'?6:3.5);if((blocked||needRise||danger)&&runner.grounded)jump=true;else if((needRise||danger||runner.wall)&&!runner.grounded&&runner.airJump&&(difficulty==='hard'||difficulty==='impossible'))jump=true;return{ix,jump}}
function update(dt){if(state!=='playing'||paused)return;elapsed+=dt;dangerPulse=Math.max(0,dangerPulse-dt);attackTimer=Math.max(0,attackTimer-dt);flash=Math.max(0,flash-dt*1.7);shake=Math.max(0,shake-dt*2.2);updateParticles(dt);if(selectedRole==='runner')moveRunner(dt,(held.left?-1:0)+(held.right?1:0),held.jump);else{const ai=botRunnerInput(dt);moveRunner(dt,ai.ix,ai.jump)}if(state!=='playing')return;if(selectedRole==='block')updateBlockRepeat(dt);if(current){if(selectedRole==='runner'){aiThink-=dt;if(aiThink<=0)chooseBlockPlan()}aimTime-=dt;if(aimTime<=0)commitCurrent()}fallingPieces.sort((a,b)=>b.y-a.y);for(let i=0;i<fallingPieces.length;i++){const p=fallingPieces[i],prev=p.y,target=landingY(p);p.y=Math.min(target,p.y+DROP_SPEED*dt);resolveCrush(p,prev,p.y);if(state!=='playing')return;if(p.y>=target-.0001){if(!lockPiece(p))return;fallingPieces.splice(i,1);i--}}const flight=fallingPieces.length;statusText.textContent=attackTimer>0?attackText:(current?`AIM ${Math.max(0,aimTime).toFixed(1)}s${flight?' · '+flight+' ↓':''}`:flight?'FALLING':'NEXT');updateQueueUI()}
