'use strict';
function updateQueueUI(){holdLabel.textContent=holdType||'—';holdLabel.style.color=holdType?COLORS[holdType]:'#f3f6ff';lineLabel.textContent=tetrisStats?.lines||0;nextPiecesEl.innerHTML=(nextQueue||[]).slice(0,3).map(t=>`<span class="qchip" style="background:${COLORS[t]}">${t}</span>`).join('')}
function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);W=r.width;H=r.height;CW=W/COLS;CH=H/ROWS}
window.addEventListener('resize',resize);
function block(x,y,color,a=1,outline=false){if(y<-1||y>ROWS)return;const px=x*CW,py=y*CH;ctx.globalAlpha=a;if(outline){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.strokeRect(px+3,py+3,CW-6,CH-6)}else{ctx.fillStyle=color;ctx.fillRect(px+1,py+1,CW-2,CH-2);ctx.fillStyle='#ffffff27';ctx.fillRect(px+2,py+2,CW-4,Math.max(2,CH*.13));ctx.fillStyle='#0000002c';ctx.fillRect(px+2,py+CH*.80,CW-4,Math.max(2,CH*.14))}ctx.globalAlpha=1}
function renderRunner(){const x=runner.x*CW,y=runner.y*CH,w=runner.w*CW,h=runner.h*CH;ctx.save();ctx.shadowColor='#ffd45f';ctx.shadowBlur=10;ctx.fillStyle='#ffd45f';const rad=Math.min(w,h)*.25;roundRect(ctx,x,y,w,h,rad);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#16192a';ctx.fillRect(x+w*.22,y+h*.27,Math.max(1,w*.12),Math.max(1,h*.09));ctx.fillRect(x+w*.66,y+h*.27,Math.max(1,w*.12),Math.max(1,h*.09));ctx.restore()}
function roundRect(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function render(){ctx.clearRect(0,0,W,H);const sx=shake>0?(rand()-.5)*shake*CW:0,sy=shake>0?(rand()-.5)*shake*CH:0;ctx.save();ctx.translate(sx,sy);ctx.fillStyle='#070a15';ctx.fillRect(-10,-10,W+20,H+20);ctx.strokeStyle='#19213a';ctx.lineWidth=1;for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*CW,0);ctx.lineTo(x*CW,H);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*CH);ctx.lineTo(W,y*CH);ctx.stroke()}ctx.fillStyle='#62edff19';ctx.fillRect(0,0,W,CH*1.05);ctx.fillStyle='#79efff';ctx.textAlign='center';ctx.font=`800 ${Math.max(8,CH*.34)}px system-ui`;ctx.fillText('▲ SUMMIT',W/2,CH*.68);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(grid[y][x])block(x,y,COLORS[grid[y][x]]);for(const p of fallingPieces)for(const c of cellsAt(p))block(c.x,c.y,COLORS[p.type],.97);if(current){const gy=landingY(current);for(const c of cellsAt(current,gy))block(c.x,c.y,COLORS[current.type],.28,true);for(const [cx,cy] of current.cells)block(current.x+cx,Math.max(0,cy-1),COLORS[current.type],.46,true)}renderRunner();renderParticles();if(attackTimer>0){ctx.font=`1000 ${Math.max(13,CH*.62)}px system-ui`;ctx.textAlign='center';ctx.fillStyle='#ffffff';ctx.shadowColor='#ff748b';ctx.shadowBlur=15;ctx.fillText(attackText,W/2,H*.35);ctx.shadowBlur=0}if(flash>0){ctx.fillStyle=`rgba(255,240,195,${Math.min(.22,flash*.5)})`;ctx.fillRect(0,0,W,H)}if(dangerPulse>0){ctx.fillStyle=`rgba(255,65,95,${Math.min(.2,dangerPulse*.23)})`;ctx.fillRect(0,0,W,H)}ctx.restore()}
function addParticle(x,y,vx,vy,life,size,color,g=0){if(particles.length>160)particles.splice(0,30);particles.push({x,y,vx,vy,life,max:life,size,color,g})}
function burstPiece(p){for(const c of cellsAt(p,Math.round(p.y)))for(let i=0;i<3;i++){const a=rand()*Math.PI*2,s=.5+rand()*1.6;addParticle(c.x+.5,c.y+.5,Math.cos(a)*s,Math.sin(a)*s,.18+rand()*.22,.04+rand()*.06,COLORS[p.type],4.5)}shake=Math.max(shake,.1)}
function burstRow(y,n){for(let x=0;x<COLS;x++)for(let i=0;i<4+n;i++){const a=rand()*Math.PI*2,s=1+rand()*2.2;addParticle(x+.5,y+.5,Math.cos(a)*s,Math.sin(a)*s,.24+rand()*.28,.045+rand()*.07,'#fff1a8',5)}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue}p.vy+=p.g*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}}
function renderParticles(){for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*CW,p.y*CH,p.size*Math.min(CW,CH),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function endGame(winner,reason){if(state!=='playing')return;state='ended';const won=winner===selectedRole;document.querySelector('#resultTitle').textContent=won?'YOU WIN':'BOT WINS';document.querySelector('#resultReason').textContent=reason;resultOverlay.classList.add('show');statusText.textContent=won?'VICTORY':'DEFEAT';tone(won?760:150,.14,.045)}
function resumeAudio(){if(!soundOn)return;try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}catch{}}
function tone(freq,dur=.05,gain=.02){if(!soundOn)return;try{resumeAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch{}}
function loop(t){if(state==='menu')return;const frame=Math.min(.05,(t-last)/1000||0);last=t;if(!paused){simAccumulator=Math.min(.08,simAccumulator+frame);let steps=0;while(state==='playing'&&simAccumulator>=FIXED_DT&&steps<MAX_STEPS){update(FIXED_DT);simAccumulator-=FIXED_DT;steps++}if(steps===MAX_STEPS)simAccumulator=0}render();requestAnimationFrame(loop)}
window.CRUSH_CLIMB_TESTS=()=>{const checks=[];checks.push(['matrix-10x20',freshGrid().length===20&&freshGrid()[0].length===10]);checks.push(['7-tetrominoes',TYPES.length===7&&new Set(TYPES).size===7]);const oldQ=nextQueue,oldSeed=seed;nextQueue=[];seed=12345;refillQueue();checks.push(['7-bag',new Set(nextQueue.slice(0,7)).size===7]);nextQueue=oldQ;seed=oldSeed;checks.push(['fixed-120hz',FIXED_DT===1/120]);checks.push(['drop-speed-8.4',DROP_SPEED===8.4]);checks.push(['aim-1.30',AIM_LIMIT===1.30]);checks.push(['srs-kicks',!!JLSTZ_KICKS['0>1']&&!!I_KICKS['0>1']]);checks.push(['small-runner',runner?.w===.58&&runner?.h===.86]);checks.push(['fair-impossible-physics',!moveRunner.toString().includes('bossRunner')&&!botRunnerInput.toString().includes('runner.vx=')]);checks.push(['crush-resolver',typeof resolveCrush==='function']);checks.push(['line-shift-resolver',typeof resolveRunnerAfterTerrainShift==='function']);checks.push(['concurrent-fall',Array.isArray(fallingPieces)]);return checks};
