'use strict';
const EPS=.0015;
function solidCell(x,y){if(x<0||x>=COLS||y>=ROWS)return true;if(y<0)return false;return !!grid[y][x]}
function aabbStatic(x,y){const l=Math.floor(x+EPS),r=Math.floor(x+runner.w-EPS),t=Math.floor(y+EPS),b=Math.floor(y+runner.h-EPS);for(let yy=t;yy<=b;yy++)for(let xx=l;xx<=r;xx++)if(solidCell(xx,yy))return true;return false}
function sweepX(dx){if(!dx)return;let target=runner.x+dx;if(dx>0){const start=Math.floor(runner.x+runner.w-EPS),end=Math.floor(target+runner.w-EPS);const t=Math.floor(runner.y+EPS),b=Math.floor(runner.y+runner.h-EPS);outer:for(let col=start+1;col<=end;col++)for(let row=t;row<=b;row++)if(solidCell(col,row)){target=Math.min(target,col-runner.w-EPS);runner.vx=0;break outer}}else{const start=Math.floor(runner.x+EPS),end=Math.floor(target+EPS);const t=Math.floor(runner.y+EPS),b=Math.floor(runner.y+runner.h-EPS);outer2:for(let col=start-1;col>=end;col--)for(let row=t;row<=b;row++)if(solidCell(col,row)){target=Math.max(target,col+1+EPS);runner.vx=0;break outer2}}runner.x=Math.max(0,Math.min(COLS-runner.w,target))}
function sweepY(dy){if(!dy)return false;let target=runner.y+dy,hit=false;if(dy>0){const start=Math.floor(runner.y+runner.h-EPS),end=Math.floor(target+runner.h-EPS);const l=Math.floor(runner.x+EPS),r=Math.floor(runner.x+runner.w-EPS);outer:for(let row=start+1;row<=end;row++)for(let col=l;col<=r;col++)if(solidCell(col,row)){target=Math.min(target,row-runner.h-EPS);runner.vy=0;hit=true;break outer}}else{const start=Math.floor(runner.y+EPS),end=Math.floor(target+EPS);const l=Math.floor(runner.x+EPS),r=Math.floor(runner.x+runner.w-EPS);outer2:for(let row=start-1;row>=end;row--)for(let col=l;col<=r;col++)if(solidCell(col,row)){target=Math.max(target,row+1+EPS);runner.vy=0;hit=true;break outer2}}runner.y=target;return hit}
function detectWall(){let wall=0;if(runner.x>.02&&aabbStatic(runner.x-.035,runner.y))wall=-1;if(runner.x<COLS-runner.w-.02&&aabbStatic(runner.x+.035,runner.y))wall=1;return wall}
function moveRunner(dt,inputX,wantJump){runner.slowTimer=Math.max(0,runner.slowTimer-dt);runner.stunTimer=Math.max(0,runner.stunTimer-dt);runner.wallClimbLock=Math.max(0,runner.wallClimbLock-dt);if(runner.stunTimer>0){inputX=0;wantJump=false}const scale=runner.slowTimer>0?.76:1,groundAccel=38,airAccel=27,maxSpeed=7.05*scale,groundFriction=29,airFriction=3.7,gravity=24,jumpV=10.05;if(inputX){runner.vx+=inputX*(runner.grounded?groundAccel:airAccel)*dt;runner.vx=Math.max(-maxSpeed,Math.min(maxSpeed,runner.vx))}else{const f=(runner.grounded?groundFriction:airFriction)*dt;runner.vx=Math.abs(runner.vx)<=f?0:runner.vx-Math.sign(runner.vx)*f}runner.jumpBuffer=Math.max(0,runner.jumpBuffer-dt);runner.coyote=runner.grounded?.165:Math.max(0,runner.coyote-dt);runner.wall=detectWall();const intoWall=(runner.wall===-1&&inputX<0)||(runner.wall===1&&inputX>0);if(runner.grounded)runner.wallClimb=Math.min(1.8,runner.wallClimb+dt*1.8);else runner.wallClimb=Math.min(1.8,runner.wallClimb+dt*.35);const climbing=runner.wall&&intoWall&&wantJump&&runner.wallClimbLock<=0&&runner.wallClimb>0;if(climbing){runner.vy=Math.min(runner.vy,-4.15);runner.wallClimb=Math.max(0,runner.wallClimb-dt);runner.airJump=true}if(wantJump&&selectedRole==='block')runner.jumpBuffer=Math.max(runner.jumpBuffer,.13);if(runner.jumpBuffer>0){if(runner.grounded||runner.coyote>0){runner.vy=-jumpV;runner.grounded=false;runner.coyote=0;runner.jumpBuffer=0;runner.airJump=true;tone(520,.035,.02)}else if(runner.wall){runner.vy=-9.4;runner.vx=-runner.wall*5.7;runner.jumpBuffer=0;tone(610,.035,.02)}else if(runner.airJump){runner.vy=-8.55;runner.airJump=false;runner.jumpBuffer=0;tone(690,.035,.018)}}const humanHolding=selectedRole==='runner'&&held.jump;const extra=(selectedRole==='runner'&&!humanHolding&&runner.vy<0)?gravity*.72:0;const apex=Math.abs(runner.vy)<1.15?.78:1;runner.vy=Math.min(11.5,runner.vy+(gravity*apex+extra)*dt);sweepX(runner.vx*dt);runner.grounded=false;const down=runner.vy>0;const yHit=sweepY(runner.vy*dt);if(down&&yHit){runner.grounded=true;runner.airJump=true;runner.wallClimb=Math.min(1.8,runner.wallClimb+.25)}if(runner.y<=.11){endGame('runner','The runner reached the summit.');return}}
function rectOverlap(ax,ay,aw,ah,bx,by,bw,bh){return ax<bx+bw&&ax+aw>bx&&ay<by+bh&&ay+ah>by}
function tryDisplaceDown(amount){const before=runner.y;sweepY(amount);return runner.y-before>=amount-.006}
function trySideEscape(cell){const center=runner.x+runner.w/2,cc=cell.x+.5;const dir=center<cc?-1:1;const target=dir<0?cell.x-runner.w-EPS:cell.x+1+EPS;if(target<0||target>COLS-runner.w||aabbStatic(target,runner.y))return false;runner.x=target;runner.vx+=dir*.45;return true}
function resolveCrush(piece,prevY,nextY){const touching=cellsAt(piece,nextY).filter(c=>rectOverlap(c.x,c.y,1,1,runner.x,runner.y,runner.w,runner.h));if(!touching.length)return false;let overhead=false,required=0;for(const c of touching){const local=piece.cells.find(([cx,cy])=>piece.x+cx===c.x&&Math.abs(nextY+cy-c.y)<.001);if(!local)continue;const prevBottom=prevY+local[1]+1;if(prevBottom<=runner.y+.22||c.y<runner.y+.18){overhead=true;required=Math.max(required,c.y+1-runner.y+EPS)}}if(!overhead){for(const c of touching)if(trySideEscape(c))return false;return false}const fallDelta=Math.max(0,nextY-prevY);required=Math.max(required,fallDelta+.012);if(required>0&&tryDisplaceDown(required)){runner.vy=Math.max(runner.vy,fallDelta*60);return false}squash();return true}
function squash(){if(runner.dead)return;runner.dead=true;dangerPulse=.9;shake=.38;tone(90,.18,.055);endGame('block','The runner was genuinely compressed between a falling piece and solid terrain.')}
function lockPiece(piece){const y=Math.round(piece.y),cells=cellsAt(piece,y);if(cells.some(c=>c.y<0)){endGame('runner','The stack reached the ceiling.');return false}for(const c of cells)if(c.y>=0)grid[c.y][c.x]=piece.type;burstPiece(piece);clearLines();return state==='playing'}
function resolveRunnerAfterTerrainShift(){if(!aabbStatic(runner.x,runner.y))return;for(let d=.04;d<=2.2;d+=.04){const up=runner.y-d;if(up>=-runner.h&&!aabbStatic(runner.x,up)){runner.y=up;runner.vy=Math.min(0,runner.vy);return}}for(let d=.04;d<=1.2;d+=.04){for(const dir of [-1,1]){const nx=runner.x+dir*d;if(nx>=0&&nx<=COLS-runner.w&&!aabbStatic(nx,runner.y)){runner.x=nx;runner.vx=0;return}}}}
function clearLines(){const rows=[];for(let y=ROWS-1;y>=0;y--)if(grid[y].every(Boolean)){rows.push(y);grid.splice(y,1);grid.unshift(Array(COLS).fill(null));if(runner.y<y)runner.y=Math.min(ROWS-runner.h,runner.y+1);y++}resolveRunnerAfterTerrainShift();const n=rows.length;if(!n){tetrisStats.combo=-1;return}tetrisStats.lines+=n;tetrisStats.combo++;const b2b=n===4&&tetrisStats.b2b;tetrisStats.b2b=n===4;const base=[0,100,300,500,800][n]||800;tetrisStats.score+=base+(b2b?400:0)+Math.max(0,tetrisStats.combo)*50;applyAttack(n,b2b);lineLabel.textContent=tetrisStats.lines;flash=.34;shake=Math.max(shake,.14+n*.055);rows.forEach(y=>burstRow(y,n));attackText=n===1?'FROST':n===2?'SHOCKWAVE':n===3?'WHITEOUT':b2b?'SUPER AVALANCHE':'AVALANCHE';attackTimer=1.0;tone(n===4?820:650+n*55,.08,.035)}
function applyAttack(n,b2b){if(n===1)runner.slowTimer=Math.max(runner.slowTimer,1);else if(n===2){runner.slowTimer=Math.max(runner.slowTimer,1.5);runner.vy=Math.max(runner.vy,3.2)}else if(n===3){runner.slowTimer=Math.max(runner.slowTimer,2);runner.wallClimbLock=Math.max(runner.wallClimbLock,1.25);runner.vy=Math.max(runner.vy,5.2)}else{runner.slowTimer=Math.max(runner.slowTimer,3);runner.wallClimbLock=Math.max(runner.wallClimbLock,b2b?3.1:2.35);runner.stunTimer=Math.max(runner.stunTimer,b2b?.58:.42);runner.airJump=false;runner.vy=Math.max(runner.vy,7)}}
